os: linux
dist: focal
language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get -y install cmake
  - sudo apt-get -y install libgtest-dev

script:
  - cmake .
  - cmake --build . -- -j2
  - bash <(curl -s https://codecov.io/bash)