os: linux
dist: focal
language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get -y install cmake
  - sudo apt-get -y install libgtest-dev

script:
  - CXX=/usr/bin/g++ CC=/usr/bin/gcc cmake . -D ENABLE_COVERAGE:BOOL=TRUE
  - cmake --build . -- -j2
  - ./testBinaryTree
  - ./testLinkedList
  - ./testStack
  - bash <(curl -s https://codecov.io/bash)